### ISSUE TITLE
[PLZ ADD] - condividere la configurazione di s.o. apache e php per poter creare un DockerFile e un'immagine su DockerHub

### ISSUE THREAD

**Issue by redblade** [REDignus/web-server#22]
ciao,
bel progetto, sarebbe possibile condividere la configurazione di s.o. + apache + php corretta per poter creare un DockerFile e un'immagine su DockerHub?

Grazie

**Comment by Lettly** [comment]
Ho pubblicato le config: https://github.com/REDignus/web-server/commit/ddaae48b5e751ebd133573f9b6810e6b6fba1c60

Qui [000-default.zip](https://github.com/REDignus/web-server/files/4348496/000-default.zip) ho messo le config di apache. Per quanto riguarda le config di php, non sono state modificate.

**Comment by Lettly** [comment]
Questa è la lista di moduli php installati:

```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```

**Comment by Lettly** [comment]
Se crei un DockerFile e un'immagine su DockerHub, apri una pull request.
